name: anywhere_overlay
description: "Anywhere Overlay: A Flutter package for customizable overlays anywhere on Android, iOS, Linux, macOS, web, and Windows."
version: 1.0.3
homepage: https://github.com/gktirkha/anywhere_overlay
repository: https://github.com/gktirkha/anywhere_overlay

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
